OXY-757: Ensure the RPK patch can't be applied in parallel by 2 processes.
This uses `flock` to check if another process has acquired the lock on
`.has_rpk_patch` in order to prevent two parallel builds from attempting to
apply the patch:

```
error: failed to run custom build command for `boring-sys v1.1.1 (/home/gabi/code/boring-rpk/boring-sys)`

Caused by:
  process didn't exit successfully: `/home/gabi/code/boring-rpk/target/debug/build/boring-sys-860f4d6bbe6cd7a5/build-script-build` (exit status: 1)
  --- stderr
  Checking patch src/include/openssl/ssl.h...
  error: while searching for:
   * OTHER ENTITY BASED ON INFRINGEMENT OF INTELLECTUAL PROPERTY RIGHTS OR
   * OTHERWISE.
   */

  #ifndef OPENSSL_HEADER_SSL_H
  #define OPENSSL_HEADER_SSL_H

  error: patch failed: src/include/openssl/ssl.h:138
  error: src/include/openssl/ssl.h: patch does not apply
  Error: Custom { kind: Other, error: "\"/home/gabi/code/boring-rpk/scripts/apply_rpk_patch.sh\" exited with status: 1" }
warning: build failed, waiting for other jobs to finish...
error: build failed
```

This error happens if the patch has already been applied:

```
 * OTHER ENTITY BASED ON INFRINGEMENT OF INTELLECTUAL PROPERTY RIGHTS OR
 * OTHERWISE.
 */
/* ====================================================================
 * Copyright 2020 Apple Inc.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the “Software”),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom
 * the Software is furnished to do so, subject to the following conditions:
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 * THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS
 * OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 */

```